FROM debian:stretch-slim

RUN useradd -ms /bin/bash sharptalk

RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        procps \
        wine \
        wine32 \
        xauth \
        xvfb \
    && rm -rf /var/lib/apt/lists/*

COPY bin/winetricks /usr/local/bin/

RUN mkdir -p /usr/share/wine/mono/ && cd /usr/share/wine/mono/ \
    && curl -O https://dl.winehq.org/wine/wine-mono/4.5.6/wine-mono-4.5.6.msi \
    && chown -R sharptalk .

USER sharptalk
ENV WINEPREFIX /home/sharptalk/.wine
ENV WINEARCH win32
# Silence all the "fixme: blah blah blah" messages from wine
ENV WINEDEBUG fixme-all
ENV DISPLAY :0
WORKDIR /home/sharptalk

RUN wineboot --init \
    && while pgrep wineserver >/dev/null; do echo "Waiting for wineserver"; sleep 1; done \
    && rm /usr/share/wine/mono/*.msi

COPY lib lib
COPY .asoundrc .
COPY bin/run.sh .

ENTRYPOINT ["./run.sh"]
